#!/bin/bash

__BX_CONSTANT_COMMAND_NAME__="bx"
__BX_CONSTANT_VERSION__="0.2.2"

# TODO: move away
__BX_CONSTANT_TRUE__=0
__BX_CONSTANT_FALSE__=1

readonly __BX_CONSTANT_COMMAND_NAME__
readonly __BX_CONSTANT_VERSION__

readonly __BX_CONSTANT_TRUE__
readonly __BX_CONSTANT_FALSE__
