#!/bin/bash

__BAKE_CONSTANT_COMMAND_NAME__="bake"
__BAKE_CONSTANT_VERSION__="0.1"

__BAKE_CONSTANT_TRUE__=0
__BAKE_CONSTANT_FALSE__=1

readonly __BAKE_CONSTANT_COMMAND_NAME__
readonly __BAKE_CONSTANT_VERSION__

readonly __BAKE_CONSTANT_TRUE__
readonly __BAKE_CONSTANT_FALSE__
