name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Generate dist
        shell: bash
        run: ./bin/bake dist
