name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - run: ./bin/bake "lint --exclude SC2317"
      - run: ./bin/bake format && git diff --exit-code

  test:
    name: Test

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v6

      - name: Test run
        id: test-run
        run: |
          ./bin/bake -q test | tee output.log

          counts=($(tail -n 1 output.log | sed -E 's/\x1b\[[0-9;]*m//g; s/\x1b\(B//g' | sed -E 's/^========= ([0-9]+) PASSED - ([0-9]+) SKIPPED - ([0-9]+) FAILED/\1 \2 \3/'))
          echo "passed-count=${counts[0]}" >> ${GITHUB_OUTPUT}
          echo "skipped-count=${counts[1]}" >> ${GITHUB_OUTPUT}
          echo "failed-count=${counts[2]}" >> ${GITHUB_OUTPUT}

          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          cat output.log >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"

      - name: Skip check
        run: |
          [[ ${{ steps.test-run.outputs.skipped-count }} -le ${{ vars.MAX_SKIPS }} ]]
