name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TERM: ""

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check style
        run: |
          ./bin/bake "lint --exclude SC2317"
          ./bin/bake format && git diff --exit-code

      - name: Check tests
        id: check-tests
        run: |
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          ./bin/bake tests | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
