name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.5'
          bundler-cache: true

      - run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - run: ./bin/bake format && git diff --exit-code
      - run: ./bin/bake "lint --exclude SC2317"
      - run: ./bin/bake cucumber-lint

  features-check:
    name: Features Check

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.5'
          bundler-cache: true

      - name: Tests run
        id: tests-run
        run: |
          ./bin/bake "features-check --tags='not @skip:${{ vars.MAX_SKIPS }}'"
